substitutions: 
  ap_password: "123456789"
  ota_password: "123456789"

esphome:
  name: garage_lights
  friendly_name: Garage Lights
  name_add_mac_suffix: true
  project:
    name: MorganMLGman.GarageLights
    version: 1.0.2

packages: 
  esp32_c3_remote:
    url: https://github.com/MorganMLGman/ESPHomeBaseFiles
    files:
      - ESP32/esp32_c3_super_mini.yaml
    ref: master
    refresh: 1d

http_request:

ota:
  - platform: esphome
    id: ota_esphome
    password: ${ota_password}
  - platform: http_request
    id: ota_http

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://morganmlgman.github.io/GarageLights/firmware/garage_lights.manifest.json

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Light Switch"

